### ISSUE TITLE
About how the png images in Test and Train are generated

### ISSUE THREAD

**Issue by ChaselLau666** [marmotlab/Context_Aware_Navigation#1]
Thank you for your outstanding work. I would like to know how the models in the test and train folders are generated. Looking forward to your answer!

**Comment by JingsongLiang** [comment]
Hi, thanks for your inquiry! For customized maps, you can check out this <a href="http://perplexingtech.weebly.com/game-dev-blog/a-random-dungeon-generator-for-phaserjs">link</a>.

**Comment by ChaselLau666** [comment]
Thank you for your answer

**Comment by Mehri510** [comment]
Hi can I have the dataset? I want to see what parameter did you use? it is just an assignment?
