### ISSUE TITLE
The reward of real scenario

### ISSUE THREAD

**Issue by qiushui0618** [marmotlab/Context_Aware_Navigation#3]
Hello, may I ask how the reward is obtained in a real scenario? According to your calculate_reward code, the shortest distance and path to the target point should be known in advance (this is obtained based on the ground truth map through the a star algorithm), but in a real scenario, there is no way to know the ground truth map in advance. How do you calculate the reward?

```
    def calculate_reward(self, astar_dist_cur_to_target, astar_dist_next_to_target, dist_to_target):
        reward = 0
        done = False
        reward -= 0.5
        reward += (astar_dist_cur_to_target - astar_dist_next_to_target) / 64
        if dist_to_target == 0:
            reward += 20
            done = True
        return reward, done
```

**Comment by JingsongLiang** [comment]
Hi, thanks for your question. the reward part is only for training, not for testing.
